sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

script:
  - set -e
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - npm run compile
  - npm test
  - npm run eslint
  - docker build -t "blutner/ocomis-user-ui:latest" .
  - docker tag "blutner/ocomis-user-ui:latest" "blutner/ocomis-user-ui:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-user-ui:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-user-ui:latest"
  - docker logout
